/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Pool;

import javafx.application.Application;
import javafx.scene.paint.Paint;
import javafx.stage.Stage;

import static Pool.Reader.parseTable;


public class App extends Application {

    public static void main(String[] args) {launch(args);}

    @Override
    public void start(Stage primaryStage) {
        GameWindow window = new GameWindow((BasicTable) parseTable());
        primaryStage.setTitle("Pool game");
        primaryStage.setScene(window.getScene());
        primaryStage.show();

        window.run();
    }
}
